// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shrimply.DataAccess.Data;

#nullable disable

namespace Shrimply.DataAccess.Migrations
{
    [DbContext(typeof(ShrimplyStoreDbContext))]
    [Migration("20230415145522_Shrimp")]
    partial class Shrimp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shrimply.Models.Shrimp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Shrimps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarCode = "12345",
                            Description = "PRL",
                            ListPrice = 0.0,
                            Name = "Pure Red Line",
                            Owner = "Cez",
                            Price = 0.0,
                            Price100 = 0.0,
                            Price50 = 0.0
                        },
                        new
                        {
                            Id = 2,
                            BarCode = "12345",
                            Description = "PBL",
                            ListPrice = 0.0,
                            Name = "Pure Black Line",
                            Owner = "Zuk",
                            Price = 0.0,
                            Price100 = 0.0,
                            Price50 = 0.0
                        },
                        new
                        {
                            Id = 3,
                            BarCode = "12345",
                            Description = "PWL",
                            ListPrice = 0.0,
                            Name = "Pure White Line",
                            Owner = "Zek",
                            Price = 0.0,
                            Price100 = 0.0,
                            Price50 = 0.0
                        });
                });

            modelBuilder.Entity("Shrimply.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Caridina"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Neocaridina"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Sulawesi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
